### ISSUE TITLE
Add your workspace to the poly tool doc

### ISSUE THREAD

**Issue by tengstrand** [jeans11/demo-rama-electric#2]
Hi!

Can I add this workspace to the [Example Systems](https://cljdoc.org/d/polylith/clj-poly/CURRENT/doc/example-systems) page of the poly tool documentation?

![demo-rama-electric](https://github.com/jeans11/demo-rama-electric/assets/631272/ca98c2da-5a51-4397-a4c3-76f9683be0ff)

If you think that is a good idea, then feel free to help me with the describing text, and you can also use the overview image if you want.

**Comment by jeans11** [comment]
Hi @tengstrand!

Yes this is a good idea!

**Comment by tengstrand** [comment]
Okay, cool, then I will add you! It would be helpful if you could come up with a short description. You can get inspiration from the other workspaces (post it here is fine, or me, tengstrand, on Clojurians on Slack).

**Comment by jeans11** [comment]
I send you a message on Clojurians slack

**Comment by tengstrand** [comment]
The workspace has been added to the [Example systems](https://cljdoc.org/d/polylith/clj-poly/0.2.19/doc/example-systems#_demo_rama_electric) page.
